apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-backend
  labels:
    app: express-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-backend
  template:
    metadata:
      labels:
        app: express-backend
    spec:
      containers:
        - name: express-backend
          image: yangzhou12138/express-backend
          ports:
            - containerPort: 6000

---
apiVersion: v1
kind: Service
metadata:
  name: express-backend
  labels:
    app: express-backend
spec:
  type: NodePort
  ports:
    - port: 6000
      protocol: TCP
      targetPort: 6000
      nodePort: 30001
  selector:
    app: express-backend
